package main

import "math/rand"

var empowerment = []string{
	"a box of cats",
	"a box of cats",
	"a box of rats",
	"a box of hamsters",
	"a box of puppies",
	"a box of puppies",
	"puppies",
	"puppies",
	"dogs dreaming of walkies",
	"a box of mice",
	"a box of meeces",
	"a box of mouses",
	"a box",
	"birthday presents",
	"caffeine",
	"Yorkshire tea",
	"Meg's fury",
	"guineapoop",
	"a vision of a world where no bark is left unwoofed",
	"31 guineapigs and counting",
	"your passion",
	"your passion",
	"electricity",
	"power",
	"walks",
	"electro-chemical energy generated by monkeys dancing on typewriters",
	"... the dark side of the sun. Deep, huh?",
	"candy",
	"the promise that, tomorrow, there will be candy...",
	"walkies",
	"walkies",
	"treats",
	"treats",
	"kibble",
	"_________ __ _____ _______!",
	"the mysteries of science, especially that one about the lead balloon...",
	"mystical energies that cannot be understood with the mind alone, only by seeing beyond the veil and reaching into infinity to discover the pervasive energy that binds and connects us all...\n\n\n\nThe force. I'm talking about the force. I'm a nerd. I wrote a footer on a webpage. Of course I'm a nerd.",
	"breakfast(**).\n\n\n\n\n\n\n\n<small>** It really <i> the most important meal of the day.</small>",
}

func poweredBy() string {
	// Choose a random "powered" message
	rand.Shuffle(len(empowerment), func(l, r int) { empowerment[l], empowerment[r] = empowerment[r], empowerment[l] })
	return empowerment[0]
}
